

services:
  - name: openbis/debian-openbis:20.10.5-EA
    alias: openbis

    variables:
      SERVER_HOST_PORT: localhost:8443
      GROUP_ID: 1000
      #CORE_PLUGINS: enabled-modules =
    pull_policy: never


image: gradle:alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME


setup:
  stage: setup
  script: curl https://openbis:8443
  retry: 3

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: gradle run --args "https://openbis:8443 admin changeit"
  services:
    - name: openbis/debian-openbis:20.10.5-EA
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

