[versions]
openbis = "20.10.5"
kotlinx-serialization = "1.4.1"
kotlinx-cli = "0.3.5"

[libraries]
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
openbis = { module = "openbis:openbis-v3-api", version.ref = "openbis" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test" }
test = { module = "org.jetbrains.kotlin:test"}
kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
kotlinxCLI = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "kotlinx-cli" }
jakartaMail = { module = "jakarta.mail:jakarta.mail-api", version = "latest.release" }
jacksonDatabind = {module = "com.fasterxml.jackson.core:jackson-databind", version = "latest.release"}
kotlinStdlib = {module="org.jetbrains.kotlin:kotlin-stdlib-jdk8"}

[plugins]
dockerCompose = { id = "com.avast.gradle.docker-compose", version = "0.16.11" }
fatJar = {id="io.ktor.plugin", version="2.2.3"}